title: Site

pages: false

fields:
  title:
    label: Title
    type:  text

  description:
    label: Description
    type:  textarea

  shop:
    label: Shop Link
    type: url

  instagram:
    label: Instagram Link
    type: url

  email:
    label: Email
    type: email
